import source from './templates.json';
export type TemplateTier = 'included' | 'premium';
export type TemplateLocale = 'en' | 'fr' | 'es' | 'nl' | 'de' | 'pl';
export interface Template {
 id: string; slug: string; name: string; tier: TemplateTier;
 description: Record<string,string>; thumbnail: string; desktopPreview: string;
 mobilePreview?: string; additionalScreenshots?: string[]; livePreviewUrl: string;
 sortOrder: number; width: number; height: number; hidden?: boolean;
}
// hidden:true entries are excluded from public listing but kept in the catalogue.
export const templates: readonly Template[] = source
 .map(item => ({...item,tier:item.tier as TemplateTier,description:item.description as Record<string,string>}))
 .filter(item => !item.hidden);
export const includedTemplates: readonly Template[] = templates.filter(item => item.tier === 'included');
export const templateCopy = {
 en: {eyebrow:'THE TEMPLATE COLLECTION',title:'A point of view.\nYours.',intro:'Explore 22 authentic DATAhome designs, from included essentials to distinctive premium directions.',all:'All',included:'Included',premium:'Premium',includedCollection:'22 designs for your DATAhome website',previous:'Previous template',next:'Next template',choose:'Choose a template',browse:'Template gallery',hint:'Drag, swipe or use the arrow keys to explore.',live:'View live preview',external:'Opens in a new tab',preview:'Website preview',collection:'Explore the collection',selected:'Selected template',metaTitle:'Real estate website templates | DATAhome',metaDescription:'Explore 22 authentic DATAhome website templates for your real estate agency.'},
 fr: {eyebrow:'LA COLLECTION DE TEMPLATES',title:'Un point de vue.\nLe vôtre.',intro:'Explorez 22 designs DATAhome authentiques, des essentiels inclus aux directions Premium les plus distinctives.',all:'Tous',included:'Inclus',premium:'Premium',includedCollection:'22 designs pour votre site DATAhome',previous:'Template précédent',next:'Template suivant',choose:'Choisir un template',browse:'Galerie de templates',hint:'Glissez ou utilisez les flèches du clavier pour explorer.',live:'Voir le site en direct',external:'S’ouvre dans un nouvel onglet',preview:'Aperçu du site',collection:'Explorer la collection',selected:'Template sélectionné',metaTitle:'Templates de sites immobiliers | DATAhome',metaDescription:'Explorez 22 templates DATAhome authentiques pour votre agence immobilière.'},
 es: {eyebrow:'LA COLECCIÓN DE TEMPLATES',title:'Un punto de vista.\nEl tuyo.',intro:'Explora 22 diseños auténticos de DATAhome, desde los esenciales incluidos hasta las direcciones Premium más distintivas.',all:'Todos',included:'Incluido',premium:'Premium',includedCollection:'22 diseños para tu sitio DATAhome',previous:'Template anterior',next:'Template siguiente',choose:'Elegir un template',browse:'Galería de templates',hint:'Desliza o usa las teclas de flecha para explorar.',live:'Ver el sitio en directo',external:'Se abre en una nueva pestaña',preview:'Vista previa del sitio',collection:'Explorar la colección',selected:'Template seleccionado',metaTitle:'Templates de sitios inmobiliarios | DATAhome',metaDescription:'Explora 22 templates auténticos de DATAhome para tu agencia inmobiliaria.'},
 nl: {eyebrow:'DE TEMPLATECOLLECTIE',title:'Een standpunt.\nHet jouwe.',intro:'Ontdek 22 authentieke DATAhome-ontwerpen, van inbegrepen essentials tot de meest onderscheidende Premium richtingen.',all:'Alle',included:'Inbegrepen',premium:'Premium',includedCollection:'22 ontwerpen voor uw DATAhome-website',previous:'Vorig template',next:'Volgend template',choose:'Kies een template',browse:'Templategalerij',hint:'Veeg of gebruik de pijltoetsen om te verkennen.',live:'Bekijk live preview',external:'Opent in een nieuw tabblad',preview:'Website preview',collection:'Verken de collectie',selected:'Geselecteerd template',metaTitle:'Templates voor vastgoedwebsites | DATAhome',metaDescription:'Ontdek 22 authentieke DATAhome-templates voor uw makelaarskantoor.'},
 de: {eyebrow:'DIE TEMPLATE-KOLLEKTION',title:'Ein Standpunkt.\nDeiner.',intro:'Entdecke 22 authentische DATAhome-Designs, von enthaltenen Essentials bis zu den markantesten Premium-Richtungen.',all:'Alle',included:'Enthalten',premium:'Premium',includedCollection:'22 Designs für deine DATAhome-Website',previous:'Vorheriges Template',next:'Nächstes Template',choose:'Template wählen',browse:'Template-Galerie',hint:'Wische oder nutze die Pfeiltasten zum Erkunden.',live:'Live-Vorschau anzeigen',external:'Öffnet in einem neuen Tab',preview:'Website-Vorschau',collection:'Kollektion erkunden',selected:'Ausgewähltes Template',metaTitle:'Immobilien-Website-Templates | DATAhome',metaDescription:'Entdecke 22 authentische DATAhome-Templates für deine Immobilienagentur.'},
 pl: {eyebrow:'KOLEKCJA SZABLONÓW',title:'Punkt widzenia.\nTwój.',intro:'Odkryj 22 autentyczne projekty DATAhome, od podstawowych w zestawie po najbardziej wyróżniające się kierunki Premium.',all:'Wszystkie',included:'W zestawie',premium:'Premium',includedCollection:'22 projekty dla Twojej strony DATAhome',previous:'Poprzedni szablon',next:'Następny szablon',choose:'Wybierz szablon',browse:'Galeria szablonów',hint:'Przesuń lub użyj klawiszy strzałek do eksploracji.',live:'Zobacz podgląd na żywo',external:'Otwiera się w nowej karcie',preview:'Podgląd strony',collection:'Odkryj kolekcję',selected:'Wybrany szablon',metaTitle:'Szablony stron internetowych dla nieruchomości | DATAhome',metaDescription:'Odkryj 22 autentyczne szablony DATAhome dla Twojej agencji nieruchomości.'}
} as const;
