import Image from 'next/image';
import Link from 'next/link';
import { commercial } from '@/lib/marketing/commercial';
import s from './PartnersPage.module.css';

type Locale='en'|'fr'|'es'|'nl'|'de'|'pl';
type Flow={eyebrow:string;title:string;body:string;sourceLabel:string;sources:string[];mapping:string;standardized:string;fields:string[];destinationLabel:string;destinations:string[];note:string};
type Copy={metaTitle:string;metaDescription:string;hero:{eyebrow:string;title:string;body:string};mapper:{eyebrow:string;title:string;body:string;alt:string};xml:Flow&{price:string;none:string};verified:{eyebrow:string;label:string;title:string;body:string;alt:string};crm:Flow;mini:{have:string;none:string;body:string};unified:{eyebrow:string;title:string;left:string;leftDetail:string;center:string;right:string;rightDetail:string;below:string[]};cta:{eyebrow:string;title:string;body:string;cta:string}};
function FlowDiagram({flow,kind}:{flow:Flow;kind:'xml'|'crm'}){return <div className={`${s.flow} ${s[kind]}`} role="img" aria-label={`${flow.sourceLabel}, ${flow.mapping}, ${flow.standardized}, ${flow.destinationLabel}`}><div className={s.flowSources}><span>{flow.sourceLabel}</span>{flow.sources.map(x=><small key={x}>{x}</small>)}</div><div className={s.rail} aria-hidden="true"><i/><i/><i/></div><div className={s.mapping}><em>DATAhome</em><strong>{flow.mapping}</strong></div><div className={s.rail} aria-hidden="true"><i/><i/></div><div className={s.fields}><span>{flow.standardized}</span>{flow.fields.map(x=><small key={x}>{x}</small>)}</div><div className={s.rail} aria-hidden="true"><i/><i/></div><div className={s.flowDest}><span>{flow.destinationLabel}</span>{flow.destinations.map(x=><strong key={x}>{x}</strong>)}</div></div>}
export function PartnersPage({locale,copy}:{locale:Locale;copy:Copy}){const price=new Intl.NumberFormat(locale,{style:'currency',currency:commercial.currency,maximumFractionDigits:0}).format(commercial.xmlPerFeedMonthlyEur);const fmt=(x:string)=>x.replaceAll('{xml}',price);return <article className={s.page}><header className={s.hero}><p>{copy.hero.eyebrow}</p><h1>{copy.hero.title}</h1><span>{copy.hero.body}</span></header><section className={s.mapper}><div className={s.mapperHead}><p>{copy.mapper.eyebrow}</p><h2>{copy.mapper.title}</h2><p>{copy.mapper.body}</p></div><div className={s.mapperImageWrap}><Image src="/partners/datahome-import-mapper.png" alt={copy.mapper.alt} width={1671} height={941} style={{width:'100%',height:'auto',display:'block'}}/></div></section><section className={s.section}><div className={s.head}><div><p>{copy.xml.eyebrow}</p><h2>{copy.xml.title}</h2></div><span>{copy.xml.body}</span></div><FlowDiagram flow={copy.xml} kind="xml"/><div className={s.price}><b>{fmt(copy.xml.price)}</b><span>{copy.xml.none}</span></div><aside className={s.habi}><Image src="/partner-habihub.png" alt={copy.verified.alt} width={180} height={54}/><div><p>{copy.verified.eyebrow}</p><h3>{copy.verified.label} — {copy.verified.title}</h3><span>{copy.verified.body}</span></div></aside></section><section className={s.section}><div className={s.head}><div><p>{copy.crm.eyebrow}</p><h2>{copy.crm.title}</h2></div><span>{copy.crm.body}</span></div><FlowDiagram flow={copy.crm} kind="crm"/><small className={s.note}>{copy.crm.note}</small><aside className={s.mini}><div><strong>{copy.mini.have}</strong><strong>{copy.mini.none}</strong></div><span>{copy.mini.body}</span></aside></section><section className={s.unified}><p>{copy.unified.eyebrow}</p><h2>{copy.unified.title}</h2></section><section className={s.cta}><p>{copy.cta.eyebrow}</p><h2>{copy.cta.title}</h2><span>{copy.cta.body}</span><Link href={`/${locale}/contact`}>{copy.cta.cta}<b>→</b></Link></section></article>}
